### ISSUE TITLE
typo in cleanup query

### ISSUE THREAD

**Issue by Totenfluch** [Headline22/Gangs#11]
Hey0,

I found a mistake in your "void RemoveFromGang"

`Format(sQuery3, sizeof(sQuery2), "DELETE FROM hl_gangs_statistics WHERE gang = \"%s\"", ga_sGangName[client]);`

to

`Format(sQuery3, sizeof(sQuery3), "DELETE FROM hl_gangs_statistics WHERE gang = \"%s\"", ga_sGangName[client]);`

**Comment by Headline** [comment]
Fixed. Thanks!

https://github.com/Headline22/Gangs/commit/66608f7e1a46cbd8ac847835265777009b0b6960
