### ISSUE TITLE
Rename gang

### ISSUE THREAD

**Issue by WhyFaust** [Headline22/Gangs#13]
When you change the name of the gang, it changes to a new one with quotes, correct it please.
Example
NICK change name NAME on "NEW_NAME"

**Comment by Headline** [comment]
So when a gang is renamed, quotes are added to the actual name?

**Comment by Headline** [comment]
I see the issue, try the newest beta release of 1.1.8

**Comment by WhyFaust** [comment]
Thanks, it works!
:3
