### ISSUE TITLE
Update gangs clantags

### ISSUE THREAD

**Issue by WhyFaust** [Headline22/Gangs#17]
Please do so that all the other clan tags are removed. And then I use togs for this now togsclantags. But I would not want to.

**Comment by WhyFaust** [comment]
Well, that no one had tags, except the gang.
If there is no gang, then there is no tag. If there is, then the one in which the gang.

**Comment by mrkos9i4ok** [comment]
I saw, put the latest version. Now absolutely everyone does not have a clan tag.
)

**Comment by Headline** [comment]
Did the latest update do what you wanted?

**Comment by WhyFaust** [comment]
+-
This is it, but it does not work very well.
Do not take the clan tag from the new players. Well, they just went to the server.
And not always put a clan tag gang. Or does not always clean it. But it's not exactly.

**Comment by Headline** [comment]
How about now?

**Comment by WhyFaust** [comment]
Now like normal.
There is one more nuance. If you change the clan tag in the settings directly on the server, it changes to yours and will be yours until the next round begins.

**Comment by Headline** [comment]
That's really a small thing, I'll look into it and go ahead and close this.
