### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WhyFaust** [Headline22/Gangs#18]
L 04/29/2017 - 14:08:05: [SM] Exception reported: Invalid client index (3)
L 04/29/2017 - 14:08:05: [SM] Blaming: hl_gangs_credits.smx
L 04/29/2017 - 14:08:05: [SM] Call stack trace:
L 04/29/2017 - 14:08:05: [SM]   [0] ThrowNativeError
L 04/29/2017 - 14:08:05: [SM]   [1] Line 66, hl_gangs_credits.sp::Native_GetCredits
L 04/29/2017 - 14:08:05: [SM]   [3] Gangs_GetCredits
L 04/29/2017 - 14:08:05: [SM]   [4] Line 2583, hl_gangs.sp::GetClientCredits
L 04/29/2017 - 14:08:05: [SM]   [5] Line 924, hl_gangs.sp::OpenGangsMenu
L 04/29/2017 - 14:08:05: [SM]   [6] Line 879, hl_gangs.sp::StartOpeningGangMenu
L 04/29/2017 - 14:08:05: [SM]   [7] Line 2312, hl_gangs.sp::TopGangsMenu_Callback

**Comment by WhyFaust** [comment]
+++++

//// hl_gangs.sp
//
// hl_gangs.sp(6) : warning 203: symbol is never used: "g_cvarChatTag"
// Code size:            78464 bytes
// Data size:            40420 bytes
// Stack/heap size:      16384 bytes
// Total requirements:  135268 bytes
//
// 1 Warning.
//
// Compilation Time: 0,55 sec
// ----------------------------------------

in last release

**Comment by Headline** [comment]
It's a warning from an include file. It should be ignored
