### ISSUE TITLE
no such table: hl_gangs_players

### ISSUE THREAD

**Issue by vadrozh** [Headline22/Gangs#22]
L 08/03/2017 - 15:32:24: [hl_gangs.smx] no such table: hl_gangs_statistics
L 08/03/2017 - 15:37:50: [hl_gangs.smx] no such table: hl_gangs_players

sm - 1.8.0.5919 metamod - 1.10.7

db created but size = 0 bytes

**Comment by Headline** [comment]
Try using the sql export from #21

**Comment by vadrozh** [comment]
can you give me created db? i don't know how to do it

**Comment by Headline** [comment]
There's an export in the last post of #21. Copy it and execute it as a query

**Comment by vadrozh** [comment]
i don't know how to execute query

**Comment by vadrozh** [comment]
Solved
