### ISSUE TITLE
Selection of credits system

### ISSUE THREAD

**Issue by vadrozh** [Headline22/Gangs#23]
May be you add support of selection of shops if several are available.

**Comment by vadrozh** [comment]
Also, how about doing another branch with version working not only on jb

**Comment by vadrozh** [comment]
And maybe you add sqlite support?

**Comment by Headline** [comment]
Sqlite support really won't be coming, but the selection of shops should be automatic and function well as-is if you're looking for support for a specific shop that isn't supported yet feel free to open a new issue
