### ISSUE TITLE
Make a progressive scale of prices

### ISSUE THREAD

**Issue by SHAREN** [Headline22/Gangs#24]
// for example gcv_iHealthPrice = "20", ga_iHealth[client] = 4
// gcv_fPriceModifier = 20
```sourcepawn
price = gcv_iHealthPrice.IntValue + (gcv_iPriceModifier.IntValue * ga_iHealth[client]);     // 20 + 20*4 = 100
```
I suggest doing so:
// for example gcv_fPriceModifier = 1.5
```sourcepawn
price = RoundToFloor(gcv_iHealthPrice.IntValue * Pow(gcv_fPriceModifier.FloatValue, ga_iHealth[client]*1.0));  // 20*1.5^4=101
```
on 2lvl
20 + 20*2 = 60    // before
20*1.5^2 = 45    // after
on 10 lvl 
20 + 20*10 = 220    // before
20*1.5^10 = 1153    // after

**Comment by Headline** [comment]
Done! See: #26
