### ISSUE TITLE
Gangkills are getting reset

### ISSUE THREAD

**Issue by Nachtfrische** [Headline22/Gangs#28]
The issue is that, for the second time, a gang got their kills reset to 0. They had around 8000 kills before. Is there a cap or why are they getting reset?

**Comment by Nachtfrische** [comment]
Maybe this happens, if there is an error writing to the DB and so it kinda resets the gang kills?

**Comment by Hexer10** [comment]
Sometimes ago, I had this issue too.

**Comment by JakubKosmaty** [comment]
Same problem

**Comment by Headline** [comment]
Interesting. At first glance I can't see where this issue is coming from. I'll investigate further soon

**Comment by Headline** [comment]
Should have been fixed with the last commit. Please re-open this issue if the problem consists
