### ISSUE TITLE
Gangkills are still getting reset

### ISSUE THREAD

**Issue by Nachtfrische** [Headline22/Gangs#29]
Hello,

even though I'm using the latest version, which supposedly fixes this bug, it's still not working. Today, one of my players got his kills reset again. We had some issues with our DB today, so it might have something to do with that. However, only one gang got reset. There is still an error somewhere which incorrectly updates the rows.

**Comment by Headline** [comment]
Thanks for bringing this back up. I will investigate.

**Comment by Headline** [comment]
@Nachtfrische Another hole in ctkills resets has been patched. Please let me know if the latest commit solves this issue. Thanks for your patience

**Comment by Nachtfrische** [comment]
Wow, thanks for still investing time into this issue, I'll put the new version on our server and inform you of any bugs. I'm going to close this issue for now, just because this bug isn't as common and might take months to reoccur (if at all).
