### ISSUE TITLE
Inviting two people at the same time breaks the max player limit

### ISSUE THREAD

**Issue by Nachtfrische** [Headline22/Gangs#37]
A user reported this interesting bug to me:

According to him, he had 14 out of 15 max people in his gang and invited two people. Both accepted and he now has 16/15 people. In theory, this could be abused even further by having one open spot and then inviting as many players as you could so you would get over the player limit.

Before accepting the invite, a check should be made to verify that the gang is not full and still has an open spot for a player join.

**Comment by Headline** [comment]
It looks like these checks are in place, do you happen to have size disabled? It still shows the size regardless of the fact that it's "limitless"

I've made a change regarding that clarification #38, if that is what the issue is

**Comment by Nachtfrische** [comment]
The size is enabled, maybe it was just a database quirk, I don't know since I didn't try to reproduce the issue. So far, I didn't hear anyone else complain about this issue, so I'm going to close this.

Thanks!
