### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dzagu** [Headline22/Gangs#39]
L 07/31/2018 - 19:00:44: [SM] Blaming: hl_gangs.smx
L 07/31/2018 - 19:00:44: [SM] Call stack trace:
L 07/31/2018 - 19:00:44: [SM]   [0] DBResultSet.FetchString
L 07/31/2018 - 19:00:44: [SM]   [1] Line 2394, hl_gangs.sp::SQL_Callback_GangStatistics
L 07/31/2018 - 19:05:08: [SM] Exception reported: Client 11 is not connected

**Comment by Nachtfrische** [comment]
Doesn't seem like a major error to me and shouldn't affect anything. 
The last exception is also 5 minutes later than the first few lines.

**Comment by Headline** [comment]
@dzagu this error is spliced and incomplete. I'll gladly fix any stack traces, feel free to re open once you have a solid one.
