### ISSUE TITLE
Disbanding a gang prevents gang creation

### ISSUE THREAD

**Issue by Nachtfrische** [Headline22/Gangs#40]
Hello,

if you create a gang and disband it, you can't create a new gang anymore.
Well, technically you can, but the gang will not be stored in the database or listed in the "top gangs" list. It also says that there are 0 members in the gang, even though others can join.

Since the gang isn't saved in the database, the gang disappears after reconnect or map change.

**Steps to reproduce:**
Create gang "my-gang" -> disband "my-gang"  -> create gang "new-gang" 

DB entries for "my-gang" are created and then deleted, but no entries for "new-gang" are created.

**Comment by Headline** [comment]
are there any errors in logs?

**Comment by Nachtfrische** [comment]
Indeed, this is what I found in the logs:

L 08/26/2018 - 01:45:14: [SM] Exception reported: Current result set has no fetched rows
L 08/26/2018 - 01:45:14: [SM] Blaming: hl_gangs.smx
L 08/26/2018 - 01:45:14: [SM] Call stack trace:
L 08/26/2018 - 01:45:14: [SM]   [0] DBResultSet.FetchString
L 08/26/2018 - 01:45:14: [SM]   [1] Line 2383, hl_gangs.sp::SQL_Callback_GangStatistics

**Comment by Nachtfrische** [comment]
Take this error with a grain of salt though, it doesn't line up with the times I tried to reproduce the issue.

EDIT: The above mentioned error probably happens, when someone creates a "buggy" gang, like "new-gang" from the example, and then invites users into it. The exception is then thrown because there are no entries for that gang in the database.

**Comment by Headline** [comment]
There should *hopefully* be more, specifically when the new gang is created. Does such a log exist?

**Comment by Nachtfrische** [comment]
Unfortunately not, this is the only error in my error log file, unless there is another file I'm completly missing here.

The weird thing is that the plugin successfully recognizes the gang being created and everything behaves normally, the only thing missing are the database entries.

**Comment by Headline** [comment]
Reported to be fixed by 10fe465377c25df0ff90824e472ae76910d4a4c3
