### ISSUE TITLE
I can't compile the plugin

### ISSUE THREAD

**Issue by wydome** [Headline22/Gangs#48]
I can't compile the plugin, it gives the following error: scripting\include\lastrequest.inc(105) : fatal error 196: deprecated syntax; see https://wiki.alliedmods.net/SourcePawn_Transitional_Syntax#Typedefs

All the syntaxes in the shop file are deprecated

**Comment by Headline** [comment]
you must use an older compiler, try a 1.9 one

**Comment by wydome** [comment]
Thank you, start compiling, now another problem. Changes to the .sp file are not applied after compilation, which may be a problem, compilation follows the instructions: https://hlmod.ru/threads/sourcepawn-urok-2-ustanovka-i-kompiljacija-plaginov.36888/

**Comment by Headline** [comment]
This is probably a good thing to get help for on the alliedmodders Scripting forum @ [alliedmods.net](http://forums.alliedmods.net)
