### ISSUE TITLE
Gang invites and another

### ISSUE THREAD

**Issue by ReniMal** [Headline22/Gangs#7]
If gang leader invite at the one moment more players and if they accept at the same time , in that gang can join more people than slots available. 
Need to fix menu. Because promote or check who is in your gang its not available.
Idea: Try to add colours on differents gangs, in this fact you can separate gangs.
Another idea: Add like !gangmenu here you could select in one round one boost like: speed, bigger knife dmg, hp or gravity

**Comment by Headline** [comment]
Fixed [here](https://github.com/Headline22/Gangs/commit/e487ce6b4deb16ec9cf6226b600d0e3fa53964ff)
