### ISSUE TITLE
don`t work plugin

### ISSUE THREAD

**Issue by WhyFaust** [Headline22/Gangs#8]
Error list:
L 02/28/2017 - 13:28:44: [SM] Exception reported: Language phrase "GangAlert" not found
L 02/28/2017 - 13:28:44: [SM] Blaming: hl_gangs.smx
L 02/28/2017 - 13:28:44: [SM] Call stack trace:
L 02/28/2017 - 13:28:44: [SM]   [0] VFormat
L 02/28/2017 - 13:28:44: [SM]   [1] Line 2603, hl_gangs.sp::PrintToGang
L 02/28/2017 - 13:28:44: [SM]   [2] Line 428, hl_gangs.sp::Timer_AlertGang
L 02/28/2017 - 13:28:51: [SM] Exception reported: Native is not bound
L 02/28/2017 - 13:28:51: [SM] Blaming: hl_gangs.smx
L 02/28/2017 - 13:28:51: [SM] Call stack trace:
L 02/28/2017 - 13:28:51: [SM]   [1] Gangs_GetCredits
L 02/28/2017 - 13:28:51: [SM]   [2] Line 2439, hl_gangs.sp::GetClientCredits
L 02/28/2017 - 13:28:51: [SM]   [3] Line 825, hl_gangs.sp::OpenGangsMenu
L 02/28/2017 - 13:28:51: [SM]   [4] Line 780, hl_gangs.sp::StartOpeningGangMenu
L 02/28/2017 - 13:28:51: [SM]   [5] Line 760, hl_gangs.sp::Command_Gang
L 02/28/2017 - 13:28:55: [SM] Exception reported: Native is not bound
I`m use last version

**Comment by Headline** [comment]
You didn't install the required translation files

**Comment by WhyFaust** [comment]
And where to find it?

**Comment by Headline** [comment]
Download from the releases page

**Comment by WhyFaust** [comment]
hl_gangs.zip don`t open
Only source code

**Comment by Headline** [comment]
Works fine on my end

**Comment by WhyFaust** [comment]
Now yes!)
