### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by WhyFaust** [Headline22/Gangs#9]
1)+ Adding  clan\chat gangs tags.
2)+ Adding set gang player model
3)+ Adding Throwing knives
4)+ Adding Grenades
5)+ Adding colors chat gang tag
6)+ Adding give/tagecredits command in adminmenu or gang menu(Root) and pick player list to give
7)+ Rename give/tagecredits command as my store plugin use their

**Comment by Headline** [comment]
These all seem like they'd be good external plugins to add functionality on the main one, so they'll not be added to the core plugin.

**Comment by WhyFaust** [comment]
What about 7?

**Comment by Headline** [comment]
Can you be more specific about it

**Comment by Headline** [comment]
I'm gonna go ahead and close this for now. Feel free to reopen to explain to me number 7 in more detail

**Comment by WhyFaust** [comment]
7)i`m use plugin shop(frozdark) 
And, when I write a command for example !givecredits {name} 1000
That to me 1000 credits is given both in a gang and in shop at once
It can be done like this: sm_givegangscredits and so on

**Comment by Headline** [comment]
Oh. If that shop has an include file for developers send it to me, I'm okay with supporting private shops in this plugin.

**Comment by shanapu** [comment]
frozdark: https://github.com/shanapu/MyJailshop/blob/master/addons/sourcemod/scripting/include/shop.inc
https://github.com/shanapu/MyJailshop/tree/master/addons/sourcemod/scripting/include/shop

**Comment by Headline** [comment]
shanapu, is this seperate from myjailshop? Why are you sharing repositories with it.

EDIT: Oh. I see what you're doing. Let me push a patch

**Comment by Headline** [comment]
Does this look good?

https://github.com/Headline22/Gangs/pull/10
